version: '3'
services:
  sip_db:
    image: mariadb:10.5
    container_name: sip_db
    environment:
      MYSQL_DATABASE: sip
      MYSQL_ROOT_PASSWORD: sip
    ports:
      - "3306:3306"
    volumes:
      - sip_db_data:/var/lib/mysql
    restart: always
  sip_drupal:
    depends_on:
      - sip_db
    build: .
    container_name: sip
    ports:
      - "8080:80"
    volumes:
      - .:/app
    restart: always
volumes:
  sip_db_data:
